def test_first_try():
    print("Hello World!")


# class TestUserLogin:

#     def test_1(self):
#         ...

#     def test_2(self):
#         ...


# def test_assert_positive_case():  # Новый тест, которые проверяет положительный кейс
#     assert (2 + 2) == 4  # Ожидается, что тест пройдет
#     assert (3 + 3) == 6  # Ожидается, что тест пройдет
#     assert (5 + 5) == 1  # Ожидается, что тест пройдет
#     assert (4 + 4) == 8  # Ожидается, что тест пройдет
#     assert (1 + 1) == 1  # Ожидается, что тест пройдет


# def test_assert_negative_case():  # Новый тест, которые проверяет негативный кейс
#     assert (2 + 2) == 5, "2 + 2 != 5" # Тут должна быть ошибка


